# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_digest',
            field=models.TextField(null=True, verbose_name='摘要'),
        ),
    ]
