# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 14:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_main_digest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加评论时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改评论时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误!')], verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('integral', models.SmallIntegerField(default=0, verbose_name='积分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.PositiveIntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Article', verbose_name='所属文章'),
        ),
    ]
