# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blogs.Tag', verbose_name='标签'),
        ),
    ]
